apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- ../../base
# Uncomment to add custom css as a configmap
# - ../../css 

namespace: open-microtools

images:
- name: ghcr.io/openmicrotools/jwt-inspect
  newTag: latest

patchesStrategicMerge:
  - service-patch.yaml
